name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 19 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_TIME_API_KEY }}
          GH_TOKEN: ${{ secrets.WAKA_TIME_SECRET }}
          LOCALE: "ko"
          SYMBOL_VERSION: 1
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
